platform :ios, '5.0'
#pod 'ios4me', :path => '~/Projets/SmartnSoft/ios4me'
#pod 'ios4me', :git => 'https://github.com/smartnsoft/ios4me.git', :commit => '40d242c725'
#pod 'ios4me', :git => 'https://github.com/smartnsoft/ios4me.git', :tag => '1.0.2'
pod 'ios4me', 						'1.0.2'
pod 'ios4me-ext-smartad/MBrand',    '1.0.3'
pod 'ios4me-ext-smartad/AdMob',     '1.0.3'
pod 'ios4me-ext-smartad/iAd',       '1.0.3'
pod 'ios4me-ext-smartad/mOcean',    '1.0.3'

pod 'ios4me-ext-smartcommand',      '1.0.0'

pod 'ios4me-ext-smartparser', 		'1.0.0'

pod 'Capptain-SDK', '1.13.0'
